version: '3.8'

services:
  firmware-server:
    build: .
    container_name: firmware-server
    restart: unless-stopped
    ports:
      - "${FIRMWARE_PORT:-8080}:80"
    volumes:
      - ./firmware:/usr/share/nginx/html/firmware:ro
      - ./html/data:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs:/var/log/nginx
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firmware.rule=Host(`flasher.schwarzes-seelenreich.de`) && PathPrefix(`/backend`)"
      - "traefik.http.routers.firmware.tls=true"
      - "traefik.http.routers.firmware.tls.certresolver=letsencrypt"

networks:
  default:
    name: firmware-network
