version: '3.8'

services:
  firmware-server:
    image: nginx:alpine
    container_name: firmware-server
    ports:
      - "8080:80"
    volumes:
      - ./firmware:/usr/share/nginx/html/firmware:ro
      - ./data:/usr/share/nginx/html/data:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

networks:
  firmware-network:
    driver: bridge
